### ISSUE TITLE
IAM Password Scanner throws exception if no password policy is set

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#14]
**Describe the bug**

If no password policy is set in IAM in an AWS account, the AwsIamPasswordPolicyScanner throws an exception while fetching the default policy:

```
software.amazon.awssdk.services.iam.model.NoSuchEntityException: The Password Policy with domain name XXXXXXX cannot be found. (Service: Iam, Status Code: 404, Request ID: 505b392c-e9a8-4ddf-8556-2fa93ee05916)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:63) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:115) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:88) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:44) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:51) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:33) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:79) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:205) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44) ~[sdk-core-2.4.4.jar:?]
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55) ~[aws-core-2.4.4.jar:?]
	at software.amazon.awssdk.services.iam.DefaultIamClient.getAccountPasswordPolicy(DefaultIamClient.java:3500) ~[iam-2.4.4.jar:?]
	at software.amazon.awssdk.services.iam.IamClient.getAccountPasswordPolicy(IamClient.java:5874) ~[iam-2.4.4.jar:?]
	at io.clouditor.discovery.aws.AwsIamPasswordPolicyScanner.list(AwsIamPasswordPolicyScanner.java:52) ~[clouditor-engine-aws-0.9-SNAPSHOT.jar:?]
	at io.clouditor.discovery.Scanner.scan(Scanner.java:103) [clouditor-engine-core-0.9-SNAPSHOT.jar:?]
	at io.clouditor.discovery.DiscoveryService.lambda$startScan$1(DiscoveryService.java:150) [clouditor-engine-core-0.9-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
1. Use an existing or new AWS account
2. Go to IAM and delete the password policy

**Expected behavior**

The expected behavior would be that no policy is discovered. However, that will incorrectly validate the password rules as "ok", where as there are no password rules defined at all (which is bad)!

**Additional context**

It seems the logical way to deal with this would be to move the password policy into a sub-resource of a scanner that scans the AWS *account*, for example together with the `AwsCloudTrailAccountScanner`. However, that scanner needs access to two different AWS clients (thank you amazon for dedicated service clients... gnarf).

**Comment by oxisto** [comment]
Legacy issue
