### ISSUE TITLE
Segmentation violation if user is not logged in

### ISSUE THREAD

**Issue by garuppel** [clouditor/clouditor#536]
If the user is not logged in and a the discovery is started by `cl service discovery start` an segmentation violation occurs. 

``` 
Clouditor$ cl service  discovery start

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x248 pc=0x786dde]

goroutine 1 [running]:
google.golang.org/grpc.(*ClientConn).Invoke(0xe12880, {0xa5dce0, 0xc000136000}, {0x9a389e, 0xc0001dfd00}, {0x92bda0, 0xc00024a660}, {0x932a00, 0xc00024a690}, {0x0, ...})
        /home/schneider/go/pkg/mod/google.golang.org/grpc@v1.44.0/call.go:32 +0x5e
clouditor.io/clouditor/api/discovery.(*discoveryClient).Start(0xc000226ce0, {0xa5dce0, 0xc000136000}, 0xa4b4b8, {0x0, 0x0, 0x0})
        /home/schneider/daten/projekt/Clouditor2/clouditor/api/discovery/discovery_grpc.pb.go:41 +0xce
clouditor.io/clouditor/cli/commands/service/discovery.NewStartDiscoveryCommand.func1(0xc00023d680, {0x994ca2, 0x0, 0x0})
        /home/schneider/daten/projekt/Clouditor2/clouditor/cli/commands/service/discovery/discovery.go:57 +0xb6
github.com/spf13/cobra.(*Command).execute(0xc00023d680, {0xe42328, 0x0, 0x0})
        /home/schneider/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ff400)
        /home/schneider/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/schneider/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        /home/schneider/daten/projekt/Clouditor2/clouditor/cmd/cli/cl.go:76 +0x1f
```

**Comment by garuppel** [comment]
@oxisto @lebogg Has anyone of you fixed the bug? I do not have it anymore.

**Comment by oxisto** [comment]
Maybe it got fixed by accident :D

**Comment by lebogg** [comment]
I don't think it is gone. It somehow occurs at the first time of STH. I got it also once but then as soon I was logged once, it never occurred again. But now within the PR review of #520 I got it again (after doing `cl service discovery start` without login`):
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6bbe82]

goroutine 1 [running]:
encoding/json.(*encodeState).marshal.func1()
        /usr/local/go/src/encoding/json/encode.go:328 +0x6e
panic({0x9d1740, 0xf70100})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
golang.org/x/oauth2.retrieveToken({0xb62508, 0xc000038100}, 0xa8193a, 0xd)
        /home/nico/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220223155221-ee480838109b/token.go:157 +0x22
golang.org/x/oauth2.(*tokenRefresher).Token(0xc00024e8d0)
        /home/nico/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220223155221-ee480838109b/oauth2.go:270 +0x1a5
golang.org/x/oauth2.(*reuseTokenSource).Token(0xc00009d160)
        /home/nico/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20220223155221-ee480838109b/oauth2.go:304 +0xd5
clouditor.io/clouditor/cli.(*Session).MarshalJSON(0xc0000b0be0)
        /home/nico/GolandProjects/clouditor/cli/session.go:176 +0x2e
encoding/json.marshalerEncoder(0xc00004e500, {0xa6d240, 0xc000010450, 0x1000000009eeae0}, {0x1, 0x4})
        /usr/local/go/src/encoding/json/encode.go:479 +0xbe
encoding/json.ptrEncoder.encode({0xc000010460}, 0xc00004e500, {0x9815a0, 0xc000010450, 0x9815a0}, {0x30, 0x0})
        /usr/local/go/src/encoding/json/encode.go:945 +0x27e
encoding/json.(*encodeState).reflectValue(0x0, {0x9815a0, 0xc000010450, 0x40ea07}, {0x78, 0x0})
        /usr/local/go/src/encoding/json/encode.go:360 +0x78
encoding/json.(*encodeState).marshal(0xc00003f1d0, {0x9815a0, 0xc000010450}, {0x80, 0x1})
        /usr/local/go/src/encoding/json/encode.go:332 +0xfa
encoding/json.(*Encoder).Encode(0xc0001e7c20, {0x9815a0, 0xc000010450})
        /usr/local/go/src/encoding/json/stream.go:206 +0x7e
clouditor.io/clouditor/cli.(*Session).Save(0xc0000b0be0)
        /home/nico/GolandProjects/clouditor/cli/session.go:161 +0x293
clouditor.io/clouditor/cli.ContinueSession()
        /home/nico/GolandProjects/clouditor/cli/session.go:132 +0x26c
clouditor.io/clouditor/cli/commands/service/discovery.NewStartDiscoveryCommand.func1(0xc000241900, {0xa7aa1e, 0x0, 0x0})
        /home/nico/GolandProjects/clouditor/cli/commands/service/discovery/discovery.go:57 +0x26
github.com/spf13/cobra.(*Command).execute(0xc000241900, {0xfba6f8, 0x0, 0x0})
        /home/nico/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001bd680)
        /home/nico/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/nico/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
main.main()
        /home/nico/GolandProjects/clouditor/cmd/cli/cl.go:76 +0x1f
```

**Comment by oxisto** [comment]
Yes, this might occur (once), because the structure of the session file has changed in #520. I would sort of ignore this and it can be fixed by just deleting the `~/.clouditor/session.json`.

**Comment by oxisto** [comment]
Ah nvm, this occurs when *updating* it and no token is set. In this case, it should not be saved at all. I will check.
