### ISSUE TITLE
Properly handle OAuth errors

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#58]
**Describe the bug**

For example, if the issuer is not valid, a internal server error is thrown. However, it should be a 401 or something else, see OAuth docs.

```
clouditor_1    | Caused by: com.auth0.jwt.exceptions.InvalidClaimException: The Claim 'iss' value doesn't match the required one.
clouditor_1    |        at com.auth0.jwt.JWTVerifier.assertValidStringClaim(JWTVerifier.java:424) ~[java-jwt-3.4.0.jar:?]
clouditor_1    |        at com.auth0.jwt.JWTVerifier.verifyClaims(JWTVerifier.java:382) ~[java-jwt-3.4.0.jar:?]
clouditor_1    |        at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:355) ~[java-jwt-3.4.0.jar:?]
clouditor_1    |        at io.clouditor.oauth.TokenResponse.decode(TokenResponse.java:26) ~[clouditor-engine-core-1.0-SNAPSHOT.jar:?]
clouditor_1    |        at io.clouditor.oauth.OAuthResource.callback(OAuthResource.java:57) ~[clouditor-engine-core-1.0-SNAPSHOT.jar:?]
clouditor_1    |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
clouditor_1    |        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
clouditor_1    |        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
clouditor_1    |        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
clouditor_1    |        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272) ~[jersey-common-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268) ~[jersey-common-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[jersey-common-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[jersey-common-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.internal.Errors.process(Errors.java:268) ~[jersey-common-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289) ~[jersey-common-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703) ~[jersey-server-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416) ~[jersey-container-servlet-core-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370) ~[jersey-container-servlet-core-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389) ~[jersey-container-servlet-core-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342) ~[jersey-container-servlet-core-2.27.jar:?]
clouditor_1    |        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229) ~[jersey-container-servlet-core-2.27.jar:?]
clouditor_1    |        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:147) ~[grizzly-http-servlet-2.4.0.jar:2.4.0]
clouditor_1    |        ... 7 more
```

**Comment by oxisto** [comment]
Legacy issue
