### ISSUE TITLE
Clouditor does not start on Apple M1

### ISSUE THREAD

**Issue by oxisto** [clouditor/clouditor#97]
**Describe the bug**

Clouditor does not start on Apple M1 because jargon2 native implementation is not available for macOS/ARM:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/7x/03y_vsbn2ylbn8cq3w_zz_dc0000gn/T/jna--1003066738/jna3246108712943732621.tmp: dlopen(/private/var/folders/7x/03y_vsbn2ylbn8cq3w_zz_dc0000gn/T/jna--1003066738/jna3246108712943732621.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/7x/03y_vsbn2ylbn8cq3w_zz_dc0000gn/T/jna--1003066738/jna3246108712943732621.tmp: no matching architecture in universal wrapper
	/private/var/folders/7x/03y_vsbn2ylbn8cq3w_zz_dc0000gn/T/jna--1003066738/jna3246108712943732621.tmp: no matching architecture in universal wrapper
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2407)
	at java.base/java.lang.Runtime.load0(Runtime.java:747)
	at java.base/java.lang.System.load(System.java:1857)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:761)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:736)
	at com.sun.jna.Native.<clinit>(Native.java:131)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:41)
	at com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend.copyToMemory(NativeRiJargon2Backend.java:274)
	at com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend.rawHash(NativeRiJargon2Backend.java:77)
	at com.kosprov.jargon2.nativeri.backend.NativeRiJargon2Backend.encodedHash(NativeRiJargon2Backend.java:140)
	at com.kosprov.jargon2.internal.Jargon2BackendAdapter.encodedHash(Jargon2BackendAdapter.java:33)
	at com.kosprov.jargon2.internal.HasherImpl.encodedHash(HasherImpl.java:245)
	at io.clouditor.auth.AuthenticationService.hashPassword(AuthenticationService.java:107)
	at io.clouditor.auth.AuthenticationService.createDefaultUser(AuthenticationService.java:90)
	at io.clouditor.auth.AuthenticationService.init(AuthenticationService.java:77)
	at io.clouditor.Engine.init(Engine.java:169)
	at io.clouditor.Engine.start(Engine.java:237)
	at io.clouditor.EngineApplication.main(EngineApplication.kt:40)
```

**Comment by oxisto** [comment]
It seems we should switch to another argon library, since the old one seems out of date. Blocked by https://github.com/phxql/argon2-jvm/issues/78
